services:
  # 젠킨스
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    restart: always
    user: root
    container_name: jenkins
    ports:
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 중요! 호스트 도커 연결
      - ./jenkins:/var/jenkins_home

    networks:
      - home_network

networks:
  home_network:
    external: true