apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik/traefik
  repo: https://traefik.github.io/charts
  targetNamespace: kube-system
  version: "latest" # 필요한 Traefik chart 버전을 명시적으로 지정할 수 있습니다.
  valuesContent: |-
    ports:
      web:
        port: 80
        exposedPort: 80
      websecure:
        port: 443
        exposedPort: 443
      custom-8000:
        port: 8000
        exposedPort: 8000
        protocol: TCP
    additionalArguments:
      - "--entryPoints.custom-8000.address=:8000"
