apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
spec:
  replicas: {{ .Values.mysql.replica }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.auth.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
