services:
  springboot:
    image: ghkd110/server:latest
    container_name: hhs-server
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/home?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=home
      - SPRING_DATASOURCE_ROOT_PASSWORD=1234
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - hhs-network
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=home
      - MYSQL_USER=home
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
    networks:
      - hhs-network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hhs-network
    restart: always
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    container_name: rabbitmq
    networks:
      - hhs-network

networks:
  hhs-network:
    driver: bridge