# Backend Docker Compose
version: "3.7"
services:
  springboot:
    build:
      context: home_server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    container_name: home
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/home?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - home_network
networks:
  home_network:
      external: true