version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=home
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER = home
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - home_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - home_network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hhs
      POSTGRES_PASSWORD: hhs
      POSTGRES_DB: hhs
      TZ: Asia/Seoul
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - home_network

  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: tees3359@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    networks:
      - home_network

networks:
  home_network:
    external: true