certificatesResolvers:
  cloudflare:
    acme:
      email: tees3359@gmail.com
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - "1.1.1.1:53"
        - "8.8.8.8:53"
