springboot:
  image:
    repository: ghkd110/hhs-server
    tag: latest
  service:
    type: ClusterIP
    port: 8000

mysql:
  image:
    repository: mysql
    tag: 5.7
  service:
    type: ClusterIP
    port: 3306
  rootPassword: 1234
  database: home
  username: home
  password: 1234
