apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.auth.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
