apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-rabbitmq
spec:
  selector:
    app: {{ .Chart.Name }}-rabbitmq
  ports:
    - name: rabbitmq
      port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}