apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}